# Shell variables
# Generated by 'wal'
wallpaper='/home/timetraveller/Pictures/Wallpapers/wall_fuu.jpg'

# Special
background='#020204'
foreground='#eee4ec'
cursor='#eee4ec'

# Colors
color0='#020204'
color1='#966281'
color2='#6B87B5'
color3='#7696C6'
color4='#7DA1D2'
color5='#A7A6BC'
color6='#CED5E5'
color7='#eee4ec'
color8='#F2EEF5'
color9='#966281'
color10='#6B87B5'
color11='#7696C6'
color12='#7DA1D2'
color13='#A7A6BC'
color14='#CED5E5'
color15='#eee4ec'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
